name: issue-comment-workflow # 시각화 이름
on: issue_comment

jobs:
  pr-comment:
    if: ${{ github.event.issue.pull_request }} # PR에 대한 코멘트만 실행 
    runs-on: ubuntu-latest
    steps:
      - name: pr comment
        run: echo "Hello, ${{ github.actor }}. You commented on a PR."

  issue-comment:
    if: ${{ !github.event.issue.pull_request }} # PR이 아닌 이슈에 대한 코멘트만 실행 
    runs-on: ubuntu-latest
    steps:
      - name: issue comment
        run: echo "Hello, ${{ github.actor }}. You commented on an issue."
