name: multiple_event-workflow # 시각화 이름

on: 
  push:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed]
  issue_comment:
    types: [created]


jobs:
  multiple_event-job:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      - name: step1
        run: echo "Hello, ${{ github.actor }}"
      - name: step2 
        run: |
          echo "Hello, ${{ github.actor }}"
          echo "Hello, ${{ github.repository }}"