name: create-app
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'feature'
        type: choice
        options:
          - 'feature'
          - 'fix'
          - 'hotfix'
          - 'release'
      name:
        description: 'set repo name'
        required: true
        default: 'new-app'
        type: string

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create repo
        id: create-repo
        run: |
          gh repo create moonsug-action/${{ inputs.prefix }}-${{ inputs.name }} --public
      - name: slack
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "pretext": "create repo result",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "create repo result ${{ steps.create-repo.outcome }}",
                      "short": true,
                      "value": "${{ inputs.prefix }}-${{ inputs.name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
