name: path-filter
on:
  push:
    paths:
      - '.github/workflows/part1/*'
      - '!.github/workflows/part1/push.yaml' # 제외할 파일

jobs:
  path-filter-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, ${{ github.actor }}"
      - name: step2
        run: |
          echo "Hello, ${{ github.actor }}"
          echo "Hello, ${{ github.repository }}"