name: path-filter
on:
  push:
    paths:
      - '.github/workflows/part1/*'

jobs:
  path-filter-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, ${{ github.actor }}"
      - name: step2
        run: |
          echo "Hello, ${{ github.actor }}"
          echo "Hello, ${{ github.repository }}"