name: pull_request-workflow # 시각화 이름
on: pull_request

jobs:
  pull_request-job:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      - name: step1
        run: echo "Hello, ${{ github.actor }}"
      - name: step2 
        run: |
          echo "Hello, ${{ github.actor }}"
          echo "Hello, ${{ github.repository }}"