name: scrects
on: push

jobs:
  get-scrects:
    runs-on: ubuntu-latest
    steps:
      - name: echo scrects
        run: echo "screct=${{ secrets.LEVEL }}"

  get-env-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo env
        run: |
          echo "env=${{ vars.level }}"
          echo "env=${{ secrets.key }}"